[build]
builder = "nixpacks"
providers = ["nodejs"]
buildCommand = "npm install --no-package-lock"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/discovery/health"
healthcheckTimeout = 100

[variables]
NODE_ENV = "production"
